#!/usr/bin/perl
use List::Util qw(pairs);
@PAPERS = qw(
    watts2002simple         http://www.stat.berkeley.edu/~aldous/260-FMIE/Papers/watts.pdf
    newman2003structure     http://epubs.siam.org/doi/pdf/10.1137/S003614450342480
    milgram1969note         https://www.dropbox.com/s/ij30vedzdinljpo/milgram1969note.pdf?raw=1
    watts1999small          http://blacky.terra32.net/trusso/CorsoTeoriaAvanzataReti/info4/altrecose/DuncanJWattsSigma.pdf
    kempe2003maximizing     http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.407.4750&rep=rep1&type=pdf
    anderson1997information http://www.pugetsound.edu/facultypages/gmilam/courses/econ291/readings/AndersonHolt_InfoCascade.pdf
    eftekhar2013information http://www.cs.toronto.edu/~milad/paper/fp1006-eftekhar.pdf
);
for (pairs @PAPERS) {
    ($name, $url) = @$_;
    $file = "papers/$name.pdf";
    system 'wget', '-O', $file, $url unless -e $file;
}
